window.ROADMAP_TASKS = [
  {
    id: "task-001",
    title: "Audit onboarding flow friction points",
    assignee: "Maya Chen",
    role: "Product Designer",
    stream: "Growth",
    initiative: "Activation Refresh",
    objective: "Reduce first-week user drop-off",
    jiraUrl: "https://jira.example.com/browse/DES-101",
    startDate: "2026-03-02",
    endDate: "2026-03-13",
    status: "Done",
    taskType: "Research",
    notes: "Includes five moderated interviews and analytics review."
  },
  {
    id: "task-002",
    title: "Map billing settings information architecture",
    assignee: "Leo Park",
    role: "Senior Product Designer",
    stream: "Platform",
    initiative: "Billing Foundations",
    objective: "Simplify settings discoverability",
    jiraUrl: "https://jira.example.com/browse/DES-102",
    startDate: "2026-03-09",
    endDate: "2026-03-27",
    status: "In Progress",
    taskType: "UX Design",
    notes: "First pass ready for PM and support review."
  },
  {
    id: "task-003",
    title: "Create component inventory for analytics surfaces",
    assignee: "Anika Rao",
    role: "Design Systems Designer",
    stream: "Design System",
    initiative: "Analytics Consistency",
    objective: "Align patterns across dashboards",
    jiraUrl: "https://jira.example.com/browse/DES-103",
    startDate: "2026-03-16",
    endDate: "2026-04-03",
    status: "In Progress",
    taskType: "Design System",
    notes: "Tracking reusable chart wrappers, filters and table states."
  },
  {
    id: "task-004",
    title: "Prototype new empty states for projects",
    assignee: "Maya Chen",
    role: "Product Designer",
    stream: "Core Product",
    initiative: "Project Creation Experience",
    objective: "Improve activation inside workspace setup",
    jiraUrl: "https://jira.example.com/browse/DES-104",
    startDate: "2026-03-23",
    endDate: "2026-04-10",
    status: "Planned",
    taskType: "Prototype",
    notes: "Will test three content directions with lifecycle hooks."
  },
  {
    id: "task-005",
    title: "Define service blueprint for support escalation touchpoints",
    assignee: "Jonas Silva",
    role: "Staff Service Designer",
    stream: "Customer Experience",
    initiative: "Support Journey Alignment",
    objective: "Clarify ownership across escalations",
    jiraUrl: "https://jira.example.com/browse/DES-105",
    startDate: "2026-04-01",
    endDate: "2026-04-17",
    status: "Planned",
    taskType: "Service Design",
    notes: "Depends on operations interviews scheduled in week one."
  },
  {
    id: "task-006",
    title: "Run usability study on template selection",
    assignee: "Iris Novak",
    role: "UX Researcher",
    stream: "Growth",
    initiative: "Template Discovery",
    objective: "Increase template adoption rate",
    jiraUrl: "https://jira.example.com/browse/DES-106",
    startDate: "2026-04-06",
    endDate: "2026-04-24",
    status: "Planned",
    taskType: "Research",
    notes: "Eight sessions planned across new and returning customers."
  },
  {
    id: "task-007",
    title: "Refine handoff spec for mobile navigation redesign",
    assignee: "Leo Park",
    role: "Senior Product Designer",
    stream: "Mobile",
    initiative: "Navigation Modernization",
    objective: "Reduce engineering ambiguity before implementation",
    jiraUrl: "https://jira.example.com/browse/DES-107",
    startDate: "2026-04-13",
    endDate: "2026-05-01",
    status: "Planned",
    taskType: "Handoff",
    notes: "Includes responsive annotations and motion notes."
  },
  {
    id: "task-008",
    title: "Document accessibility checklist for internal reviews",
    assignee: "Anika Rao",
    role: "Design Systems Designer",
    stream: "Design System",
    initiative: "Accessibility Baseline",
    objective: "Create repeatable review criteria for all squads",
    jiraUrl: "https://jira.example.com/browse/DES-108",
    startDate: "2026-04-20",
    endDate: "2026-05-08",
    status: "Planned",
    taskType: "Documentation",
    notes: "Initial version will live alongside design QA checklist."
  },
  {
    id: "task-009",
    title: "Explore dashboard storytelling patterns for executive reports",
    assignee: "Jonas Silva",
    role: "Staff Service Designer",
    stream: "Data Experience",
    initiative: "Executive Reporting",
    objective: "Improve narrative clarity in high-level dashboards",
    jiraUrl: "https://jira.example.com/browse/DES-109",
    startDate: "2026-05-04",
    endDate: "2026-05-22",
    status: "Planned",
    taskType: "Discovery",
    notes: "Will benchmark competitor reporting flows and internal stakeholder needs."
  },
  {
    id: "task-010",
    title: "Design approval workflow states for content operations",
    assignee: "Maya Chen",
    role: "Product Designer",
    stream: "Operations",
    initiative: "Content Workflow Upgrade",
    objective: "Make review states explicit for editors and managers",
    jiraUrl: "https://jira.example.com/browse/DES-110",
    startDate: "2026-05-11",
    endDate: "2026-05-29",
    status: "Planned",
    taskType: "UX Design",
    notes: "Needs coordination with permissions work in platform squad."
  },
  {
    id: "task-011",
    title: "Validate prioritization model for research intake",
    assignee: "Iris Novak",
    role: "UX Researcher",
    stream: "Research Ops",
    initiative: "Intake Framework",
    objective: "Standardize request scoring across product areas",
    jiraUrl: "https://jira.example.com/browse/DES-111",
    startDate: "2026-05-18",
    endDate: "2026-06-05",
    status: "Planned",
    taskType: "Operations",
    notes: "Trial run with design managers before broader rollout."
  },
  {
    id: "task-012",
    title: "Prepare concept board for summer planning workshop",
    assignee: "Leo Park",
    role: "Senior Product Designer",
    stream: "Strategy",
    initiative: "Q3 Planning",
    objective: "Frame design bets for cross-functional planning",
    jiraUrl: "https://jira.example.com/browse/DES-112",
    startDate: "2026-06-01",
    endDate: "2026-06-19",
    status: "Planned",
    taskType: "Strategy",
    notes: "Board should combine customer themes, risks and concept directions."
  }
];
